
incluir = [
    "UNIVERSAL CHANNEL.mx",
    "UNIVERSAL CINEMA.mx",
    "UNIVERSAL COMEDY.mx",
    "UNIVERSAL CRIME.mx",
    "UNIVERSAL PREMIERE.mx",
    "UNIVERSAL REALITY.mx",
    "HBO.-.Eastern.Feed.us",
    "Canal.Golden.Edge.mx",
    "Canal.Golden.Edge.cl",
    "Canal.Golden.Premier.cl",
    "Starz.Cinema.HD.-.Eastern.us",
    "Univision.Telenovelas.us",
    "CINECANAL HD.cl",
    "Canal.Animal.Planet.(Chile).cl",
    "Canal.HBO.2.Latinoamérica.mx",
    "Canal.HBO.(México).mx",
    "HBO.co",
    "Canal.Sundance.TV.(España).sv",
    "SYFY.uy",
    "Canal.TNT.(México).mx",
    "Canal.TNT.Series.(México).mx",
    "Canal.Paramount.Channel.(Chile).cl",
    "Canal.Multipremier.cl",
    "Canal.HBO.Signature.Latinoamérica.ar",
    "Canal.Film.&.Arts.mx",
    "Love.Nature.co",
    "HOLA.TV.HD.uy",
    "Food.Network.co",
    "Canal.E!.Entertainment.Television.(Chile).cl",
    "Canal.HTV.cl",
    "Canal.MTV.00s.cl",
    "Canal.MTV.(Chile).cl",
    "Canal.MTV.Live.HD.cl",
    "Canal.MTV.Hits.mx",
    "Canal.Telehit.mx",
    "Canal.Telehit.Música.Plus.mx",
    "Canal.VH1.HD.(Latinoamérica).mx",
    "Canal.24.Horas.(Chile).cl",
    "Canal.CNN.Chile.cl",
    "Canal.Tooncast.cl",
    "Canal.CNN.en.Español.cl",
    "Canal.CNN.Internacional.cl",
    "Canal.Golden.Edge.mx",
    "[CL] AMC.cl",
    "[CL] AXN.cl",
    "[CL] Discovery Channel.cl",
    "[CL] Discovery Theater.cl",
    "[CL] FOX Sports.cl",
    "[CL] TyC Sports.cl",
    "AandE HD.cl",
    "AandE.cl",
    "AMC.ar",
    "AMC.co",
    "ANIMAL PLANET.mx",
    "AXN HD.cl",
    "Canal 13 HD.cl",
    "Canal.TLC.(México).mx",
    "Cartoon Network HD.cl",
    "CARTOON NETWORK.mx",
    "CARTOONITO.cl",
    "CHV.cl",
    "Canal.Cinecanal.(México).mx",
    "Cinemax.co",
    "Canal.Cinemax.(México).mx",
    "DAZN 1.es",
    "DAZN 2.es",
    "DAZN 3.es",
    "DAZN 4.es",
    "DHE HD.cl",
    "DISCOVERY CHANNEL HD.mx",
    "Discovery Familia (U.S. feed).us",
    "DISCOVERY HOME AND HEALTH.mx",
    "DISCOVERY ID HD.ar",
    "DISCOVERY ID.mx",
    "DISCOVERY KIDS HD.cl",
    "DISCOVERY SCIENCE.ar",
    "DISCOVERY TURBO.cl",
    "DISCOVERY WORLD HD.cl",
    "DISNEY CHANNEL HD.cl",
    "DISNEY JUNIOR HD.cl",
    "EL GOURMET.ar",
    "ESPN 2 HD.cl",
    "ESPN 2.cl",
    "ESPN 3 HD.cl",
    "ESPN 3.cl",
    "ESPN 3.mx",
    "ESPN 4.cl",
    "ESPN 4.mx",
    "ESPN 5.cl",
    "ESPN 6.cl",
    "ESPN 7.cl",
    "ESPN HD.cl",
    "ESPN Premium HD.cl",
    "ESPN.mx",
    "ETC TV HD.cl",
    "FOX SPORTS ARGENTINA.ar",
    "FOX SPORTS PREMIUM.mx",
    "FX HD.cl",
    "FX.mx",
    "GOLDEN HD.co",
    "HBO 2 HD.cl",
    "HBO Family HD.cl",
    "HBO MUNDI.cl",
    "HBO PLUS ESTE.cl",
    "HBO POP.cl",
    "HBO XTREME HD.cl",
    "HBO.mx",
    "HGTV.us",
    "HISTORY 2 HD.cl",
    "HISTORY CHANNEL HD.cl",
    "HOME and HEALTH HD.cl",
    "LIFETIME.mx",
    "M+ Deportes.es",
    "M+ LALIGA TV.es",
    "M+ Liga de Campeones.es",
    "NAT GEO HD.ar",
    "NAT GEO HD.cl",
    "Nat Geo Wild.es",
    "Nick Jr HD.cl",
    "NICKELODEON.cl",
    "Paramount HD.cl",
    "SONY HD.cl",
    "SONY.mx",
    "SPACE.cl",
    "SPACE.mx",
    "STAR CHANNEL HD.cl",
    "Studio Universal HD.cl",
    "TCM.cl",
    "TLC HD.cl",
    "TNT HD.cl",
    "TNT Novelas HD.cl",
    "TNT Sports.cl",
    "TVN.cl",
    "Universal HD.cl",
    "Warner HD.cl",
]
