
incluir = [
    "Canal.Cartoonito.(México).mx",
    "Canal.Golden.(México).mx",
    "Canal.Golden.Edge.mx",
    "[CL] AMC.cl",
    "[CL] AXN.cl",
    "[CL] Discovery Channel.cl",
    "[CL] Discovery Theater.cl",
    "[CL] FOX Sports.cl",
    "[CL] TyC Sports.cl",
    "AandE HD.cl",
    "AandE.cl",
    "AMC.ar",
    "AMC.co",
    "Animal Planet HD.cl",
    "ANIMAL PLANET.mx",
    "AXN HD.cl",
    "Canal 13 HD.cl",
    "Canal 13.cl",
    "Canal.TLC.(México).mx",
    "Cartoon Network HD.cl",
    "CARTOON NETWORK.mx",
    "CARTOONITO.cl",
    "CHV.cl",
    "Canal.Cinecanal.(México).mx",
    "Cinemax.co",
    "Canal.Cinemax.(México).mx",
    "DAZN 1.es",
    "DAZN 2.es",
    "DAZN 3.es",
    "DAZN 4.es",
    "DHE HD.cl",
    "DISCOVERY CHANNEL HD.mx",
    "Discovery Familia (U.S. feed).us",
    "DISCOVERY HOME AND HEALTH.mx",
    "DISCOVERY ID HD.ar",
    "DISCOVERY ID.mx",
    "DISCOVERY KIDS HD.cl",
    "DISCOVERY SCIENCE.ar",
    "DISCOVERY TURBO.cl",
    "DISCOVERY WORLD HD.cl",
    "DISNEY CHANNEL HD.cl",
    "DISNEY JUNIOR HD.cl",
    "EL GOURMET.ar",
    "ESPN 2 HD.cl",
    "ESPN 2.cl",
    "ESPN 3 HD.cl",
    "ESPN 3.cl",
    "ESPN 3.mx",
    "ESPN 4.cl",
    "ESPN 4.mx",
    "ESPN 5.cl",
    "ESPN 6.cl",
    "ESPN 7.cl",
    "ESPN HD.cl",
    "ESPN Premium HD.cl",
    "ESPN.mx",
    "ETC TV HD.cl",
    "FOX SPORTS ARGENTINA.ar",
    "FOX SPORTS PREMIUM.mx",
    "FX HD.cl",
    "FX.mx",
    "GOLDEN EDGE.mx",
    "GOLDEN HD.co",
    "HBO 2 HD.cl",
    "HBO Family HD.cl",
    "HBO MUNDI.cl",
    "HBO PLUS ESTE.cl",
    "HBO POP.cl",
    "HBO Signature.cl",
    "HBO XTREME HD.cl",
    "HBO.mx",
    "HGTV.us",
    "HISTORY 2 HD.cl",
    "HISTORY CHANNEL HD.cl",
    "HOME and HEALTH HD.cl",
    "LIFETIME.mx",
    "LOVE NATURE HD.cl",
    "M+ Deportes.es",
    "M+ LALIGA TV.es",
    "M+ Liga de Campeones.es",
    "NAT GEO HD.ar",
    "NAT GEO HD.cl",
    "Nat Geo Wild.es",
    "Nick Jr HD.cl",
    "NICKELODEON.cl",
    "Paramount HD.cl",
    "SONY HD.cl",
    "SONY.mx",
    "SPACE.cl",
    "SPACE.mx",
    "STAR CHANNEL HD.cl",
    "Studio Universal HD.cl",
    "TCM.cl",
    "TLC HD.cl",
    "TNT HD.cl",
    "TNT Novelas HD.cl",
    "TNT Sports.cl",
    "TVN.cl",
    "Universal HD.cl",
    "Warner HD.cl",
]
