name: GET_EPG

on:
  schedule:
    - cron: '0 */6 * * *'
  # push:
  #   branches: [ 'main']

jobs:

  testing:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13.1
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.1

      - name: Install dependencies on cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
              ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run iptv.py after installing dependencies
        run: |
          python iptv.py

      - name: Add and commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "EPG Updated on $(date -u)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}